server:
  port: 8263
#  port: 8264
spring:
# 相同的服务名可以进行负载均衡
  application:
    name: CONSUMER-CLIENT
# 负载均衡配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8260/eureka
# 支持断路由
feign: 
  hystrix: 
    enabled: true
    